// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUlhneft0eTaoHN6QR8b13g426EuOdt88',
    appId: '1:886089944591:web:14c87b0b6955de9cc31d7a',
    messagingSenderId: '886089944591',
    projectId: 'projectstudyroot-cda08',
    authDomain: 'projectstudyroot-cda08.firebaseapp.com',
    storageBucket: 'projectstudyroot-cda08.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATlxn9kM0GbDKDLhhv7bCU_9wF9YlHhXE',
    appId: '1:886089944591:android:f8ccc3d9e17f65f5c31d7a',
    messagingSenderId: '886089944591',
    projectId: 'projectstudyroot-cda08',
    storageBucket: 'projectstudyroot-cda08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTyFrSzOm8gG91TbAWs4tKhB3OGnFQHEA',
    appId: '1:886089944591:ios:1848539720ad5a43c31d7a',
    messagingSenderId: '886089944591',
    projectId: 'projectstudyroot-cda08',
    storageBucket: 'projectstudyroot-cda08.appspot.com',
    iosClientId: '886089944591-a01etjmgqit1kqap8866tj3tq6g7rjcn.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTyFrSzOm8gG91TbAWs4tKhB3OGnFQHEA',
    appId: '1:886089944591:ios:1848539720ad5a43c31d7a',
    messagingSenderId: '886089944591',
    projectId: 'projectstudyroot-cda08',
    storageBucket: 'projectstudyroot-cda08.appspot.com',
    iosClientId: '886089944591-a01etjmgqit1kqap8866tj3tq6g7rjcn.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1',
  );
}
